# Generated by Django 5.0.1 on 2024-01-14 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 12, 31, 35, 839301, tzinfo=datetime.timezone.utc)),
        ),
    ]
